import * as Icons from "@heroicons/react/24/solid";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-container">
        <div className="wrapper">
          <header className="nav-bar">
            <div className="pathname">
              <p>Projects</p>
              <p>/</p>
              <p>Customer Support</p>
            </div>

            <button className="nav-toggler">
              <Icons.Bars3Icon className="h-6 w-6" />
            </button>
          </header>
          <main>
            <div className="container">
              <h2>Customer Support</h2>
              {Array(20)
                .fill("")
                .map((pera, index) => (
                  <p key={index}>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Recusandae est asperiores eaque assumenda necessitatibus
                    sint labore? Ipsam consequuntur dolorem illo laudantium
                    velit, aliquid ut voluptas debitis officiis. Eligendi,
                    perspiciatis cum?
                  </p>
                ))}
            </div>
          </main>
        </div>
        <div className="sidebar">
          <div className="sidebar-nav"></div>
        </div>
      </div>
    </>
  );
}
